// games-data.js — Catálogo Gor2Games

const juegos = [
  // ── LOCALES (siempre funcionan) ──────────────────────────────────────────
  { id:"game-011", nombre:"Snake",         categoria:"arcade",       tags:["serpiente","clasico","musica"],         thumbnail:"assets/thumbs/juego-local-1.jpg", preview_video:"assets/previews/snake.mp4", embed_url:"games/juego-local-1.html",  descripcion:"Snake con gráficos mejorados, partículas y música chiptune.",                tipo:"local" },
  { id:"game-012", nombre:"Breakout Neon",       categoria:"arcade",       tags:["pelota","ladrillos","retro"],           thumbnail:"assets/thumbs/juego-local-2.jpg", preview_video:"assets/previews/breakout.mp4", embed_url:"games/juego-local-2.html",  descripcion:"Rompé todos los ladrillos con la pelota. Estética neon.",                   tipo:"local" },
  { id:"game-013", nombre:"Memory Match",        categoria:"puzzle",       tags:["memoria","cartas","parejas"],           thumbnail:"assets/thumbs/juego-local-3.jpg", embed_url:"games/juego-local-3.html",  descripcion:"Encontrá todos los pares. Entrenás la memoria.",                            tipo:"local" },
  { id:"game-014", nombre:"Space Shooter",       categoria:"accion",       tags:["naves","disparos","espacio","shooter"], thumbnail:"assets/thumbs/juego-local-4.jpg", preview_video:"assets/previews/space-shooter.mp4", embed_url:"games/juego-local-4.html",  descripcion:"5 tipos de enemigos, power-ups, partículas. Shooter espacial.",            tipo:"local" },
  { id:"game-015", nombre:"Endless Runner",        categoria:"accion",       tags:["correr","saltar","correr","saltar","ciudad","adelgazar"],     thumbnail:"assets/thumbs/juego-local-5.jpg", preview_video:"assets/previews/endless-runner.mp4", embed_url:"games/juego-local-5.html",  descripcion:"Saltá la comida chatarra. El personaje adelgaza a medida que avanzás. Bichos voladores incluidos.",    tipo:"local" },
  { id:"game-016", nombre:"2048",           categoria:"puzzle",       tags:["numeros","logica","2048"],              thumbnail:"assets/thumbs/juego-local-6.jpg", embed_url:"games/juego-local-6.html",  descripcion:"Combiná losetas para llegar al 2048. Con swipe mobile.",                   tipo:"local" },
  { id:"game-017", nombre:"Tetris",         categoria:"puzzle",       tags:["bloques","tetris","lineas"],            thumbnail:"assets/thumbs/juego-local-7.jpg", embed_url:"games/juego-local-7.html",  descripcion:"Tetris clásico con ghost piece, niveles y pausa.",                         tipo:"local" },
  { id:"game-018", nombre:"Buscaminas",          categoria:"puzzle",       tags:["minas","logica","clasico"],             thumbnail:"assets/thumbs/juego-local-8.jpg", embed_url:"games/juego-local-8.html",  descripcion:"Buscaminas propio. Fácil, Medio y Difícil. Flag con click derecho.",       tipo:"local" },
  { id:"game-019", nombre:"Wordle ES",           categoria:"puzzle",       tags:["palabras","adivinar","español"],        thumbnail:"assets/thumbs/juego-local-9.svg", embed_url:"games/juego-local-9.html",  descripcion:"Adiviná la palabra de 5 letras en 6 intentos. En español.",               tipo:"local" },
  { id:"game-020", nombre:"¡Adrián Come!",       categoria:"accion",       tags:["atrapar","comida","esquivar"],          thumbnail:"assets/thumbs/juego-local-10.jpg", embed_url:"games/juego-local-10.html", descripcion:"Ayudá a Adrián a atrapar comida y esquivar la basura.",                   tipo:"local" },
  { id:"game-022", nombre:"Impostor Online",     categoria:"multijugador", tags:["online","social","palabras","impostor"],thumbnail:"", embed_url:"impostor/index.html",        descripcion:"Impostor entre amigos. Online en tiempo real. Hasta 10 jugadores.",       tipo:"local" },
  { id:"game-024", nombre:"Gartic Phone", categoria:"multijugador", tags:["online","dibujo","adivinar","cadena","telefono"], thumbnail:"", embed_url:"gartic-phone/index.html", descripcion:"El teléfono descompuesto. Escribí una frase, dibujá lo que ves, adiviná el dibujo. Con cadenas paralelas.", tipo:"local" },

  // ── Juegos nuevos V3 ────────────────────────────────────────────────────
  { id:"game-025", nombre:"Flappy Bird",        categoria:"accion",     tags:["flappy","vuelo","arcade","habilidad"],          thumbnail:"assets/thumbs/juego-local-11.svg", embed_url:"games/juego-local-11.html",  descripcion:"Vola entre los tubos sin golpear nada. Simple, adictivo, imposible.",                       tipo:"local" },
  { id:"game-026", nombre:"Pong",          categoria:"accion",     tags:["pong","pelota","clasico","vs"],                  thumbnail:"assets/thumbs/juego-local-12.svg", embed_url:"games/juego-local-12.html",  descripcion:"El clásico Pong contra la CPU. Primero en llegar a 7 gana.",                               tipo:"local" },
  { id:"game-027", nombre:"Doodle Jump",        categoria:"accion",     tags:["doodle","plataformas","saltar","infinito"],      thumbnail:"assets/thumbs/juego-local-13.svg", embed_url:"games/juego-local-13.html",  descripcion:"Saltá de plataforma en plataforma lo más alto posible. Plataformas especiales incluidas.",  tipo:"local" },
  { id:"game-028", nombre:"Asteroids",     categoria:"accion",     tags:["asteroids","disparos","nave","espacio"],         thumbnail:"assets/thumbs/juego-local-14.svg", embed_url:"games/juego-local-14.html",  descripcion:"Destruí los asteroides antes de que te destruyan. Girá, impulsate y dispará.",             tipo:"local" },
  { id:"game-029", nombre:"War - Carta Alta",        categoria:"casual",     tags:["cartas","war","turnos","suerte"],                thumbnail:"assets/thumbs/juego-local-15.svg", embed_url:"games/juego-local-15.html",  descripcion:"El clásico juego de cartas War. Sacá la carta más alta. Cuidado con la GUERRA.",          tipo:"local" },
  { id:"game-030", nombre:"Tower Defense", categoria:"estrategia", tags:["torre","defensa","estrategia","oleadas"],        thumbnail:"assets/thumbs/juego-local-16.svg", embed_url:"games/juego-local-16.html",  descripcion:"Poné torres para defender tu base de las oleadas de enemigos. Elegí bien dónde construir.", tipo:"local" },

  // ── Batch V3 ─────────────────────────────────────────────────────────────
  { id:"game-031", nombre:"Geometry Dash",   categoria:"accion",     tags:["geometry","dash","ritmo","plataformas"],    thumbnail:"assets/thumbs/juego-local-17.svg", embed_url:"games/juego-local-17.html",  descripcion:"Saltá los obstáculos al ritmo. Un solo botón, máxima concentración.",          tipo:"local" },
  { id:"game-032", nombre:"Simon Says",      categoria:"puzzle",     tags:["simon","memoria","secuencia","colores"],    thumbnail:"assets/thumbs/juego-local-18.svg", embed_url:"games/juego-local-18.html",  descripcion:"Repetí la secuencia de colores y sonidos. ¿Hasta qué nivel llegás?",            tipo:"local" },
  { id:"game-033", nombre:"Typing Speed",     categoria:"casual",     tags:["escribir","teclado","velocidad","wpm"],     thumbnail:"assets/thumbs/juego-local-19.svg", embed_url:"games/juego-local-19.html",  descripcion:"Medí tu velocidad de escritura. Tenés 60 segundos. ¿Cuántas WPM hacés?",        tipo:"local" },
  { id:"game-034", nombre:"Trivia",     categoria:"puzzle",     tags:["trivia","preguntas","cultura","general"],   thumbnail:"assets/thumbs/juego-local-20.svg", embed_url:"games/juego-local-20.html",  descripcion:"10 preguntas de cultura general, cine, ciencia y videojuegos.",                 tipo:"local" },
  { id:"game-035", nombre:"Color Flood",      categoria:"puzzle",     tags:["colores","flood","logica","grilla"],        thumbnail:"assets/thumbs/juego-local-21.svg", embed_url:"games/juego-local-21.html",  descripcion:"Inundá todo el tablero con un solo color usando la menor cantidad de movimientos.", tipo:"local" },
  { id:"game-036", nombre:"Piedra Papel Tijera", categoria:"casual",  tags:["rpt","clasico","turnos","cpu"],             thumbnail:"assets/thumbs/juego-local-22.svg", embed_url:"games/juego-local-22.html",  descripcion:"Piedra, papel o tijera contra la CPU. 7 rondas, primero en 4 gana.",            tipo:"local" },
  { id:"game-037", nombre:"Galaga",     categoria:"accion",     tags:["galaga","aliens","shooter","clasico"],      thumbnail:"assets/thumbs/juego-local-23.svg", embed_url:"games/juego-local-23.html",  descripcion:"Destruí las oleadas de aliens antes de que bajen. Con ataques kamikaze.",        tipo:"local" },
  { id:"game-038", nombre:"Arkanoid",   categoria:"accion",     tags:["arkanoid","pelota","ladrillos","powerups"], thumbnail:"assets/thumbs/juego-local-24.svg", embed_url:"games/juego-local-24.html",  descripcion:"Breakout avanzado con power-ups: paleta ancha, multi-bola, laser y más.",       tipo:"local" },

  // ── Batch masivo V3.1 ────────────────────────────────────────────────────
  { id:"game-039", nombre:"Pac-Man",        categoria:"arcade",     tags:["pacman","fantasmas","laberinto","clasico"],   thumbnail:"assets/thumbs/juego-local-25.svg", embed_url:"games/juego-local-25.html",  descripcion:"Pacman propio con fantasmas inteligentes, power-ups y energía. WASD para mover.",            tipo:"local" },
  { id:"game-040", nombre:"Curve Fever",         categoria:"accion",     tags:["curva","multi","local","colision"],           thumbnail:"assets/thumbs/juego-local-26.svg", embed_url:"games/juego-local-26.html",  descripcion:"2 jugadores local. Trazá curvas sin chocarte. P1: flechas · P2: A/D.",                      tipo:"local" },
  { id:"game-041", nombre:"Minesweeper Plus",    categoria:"puzzle",     tags:["minas","logica","dificultad","record"],       thumbnail:"assets/thumbs/juego-local-27.svg", embed_url:"games/juego-local-27.html",  descripcion:"Buscaminas en 4 modos de dificultad con timer y records personales.",                        tipo:"local" },
  { id:"game-042", nombre:"Bubble Shooter",        categoria:"puzzle",     tags:["burbujas","disparo","colores","match"],       thumbnail:"assets/thumbs/juego-local-28.svg", embed_url:"games/juego-local-28.html",  descripcion:"Disparás burbujas para hacer grupos de 3 o más del mismo color y eliminarlas.",              tipo:"local" },
  { id:"game-043", nombre:"Crucigrama",    categoria:"puzzle",     tags:["crucigrama","palabras","español","letras"],   thumbnail:"assets/thumbs/juego-local-29.svg", embed_url:"games/juego-local-29.html",  descripcion:"Crucigrama en español. Completá todas las palabras horizontales.",                           tipo:"local" },
  { id:"game-044", nombre:"Blackjack",     categoria:"casual",     tags:["blackjack","cartas","21","casino","apuestas"],thumbnail:"assets/thumbs/juego-local-30.svg", embed_url:"games/juego-local-30.html",  descripcion:"Blackjack completo con apuestas. Llega a 21 sin pasarte. Doblar y split disponibles.",       tipo:"local" },
  { id:"game-045", nombre:"Maze Runner",          categoria:"puzzle",     tags:["laberinto","maze","logica","niveles"],        thumbnail:"assets/thumbs/juego-local-31.svg", embed_url:"games/juego-local-31.html",  descripcion:"Laberintos generados proceduralmente. Cada nivel es más grande y complejo.",                  tipo:"local" },
  { id:"game-046", nombre:"15 Puzzle",     categoria:"puzzle",     tags:["puzzle","numeros","deslizante","logica"],     thumbnail:"assets/thumbs/juego-local-32.svg", embed_url:"games/juego-local-32.html",  descripcion:"El puzzle deslizante clásico. Modos 3×3, 4×4 y 5×5 con timer y records.",                    tipo:"local" },
  { id:"game-047", nombre:"Fruit Catch",         categoria:"accion",     tags:["atrapar","canasta","frutas","esquivar"],      thumbnail:"assets/thumbs/juego-local-33.svg", embed_url:"games/juego-local-33.html",  descripcion:"Mové la canasta para atrapar frutas y esquivar las bombas. Cada nivel más rápido.",           tipo:"local" },
  { id:"game-048", nombre:"Endless Jump",          categoria:"accion",     tags:["saltar","plataformas","altura","infinito"],   thumbnail:"assets/thumbs/juego-local-34.svg", embed_url:"games/juego-local-34.html",  descripcion:"Saltá de plataforma en plataforma lo más alto posible. El tema cambia con la altura.",        tipo:"local" },

  // ── Batch V3.2 ────────────────────────────────────────────────────────────
  { id:"game-049", nombre:"Sudoku",            categoria:"puzzle",     tags:["sudoku","logica","numeros","dificultad"],   thumbnail:"assets/thumbs/juego-local-35.svg", embed_url:"games/juego-local-35.html",  descripcion:"Sudoku completo con 3 dificultades, pistas, timer y records.",                              tipo:"local" },
  { id:"game-050", nombre:"Infinite Runner",   categoria:"accion",     tags:["runner","carriles","obstaculos","velocidad"],thumbnail:"assets/thumbs/juego-local-36.svg", embed_url:"games/juego-local-36.html",  descripcion:"Esquivá obstáculos cambiando de carril. Perspectiva 3D. Cada vez más rápido.",               tipo:"local" },
  { id:"game-051", nombre:"Ajedrez",           categoria:"estrategia", tags:["ajedrez","chess","ia","estrategia"],       thumbnail:"assets/thumbs/juego-local-37.svg", embed_url:"games/juego-local-37.html",  descripcion:"Ajedrez completo contra IA. Incluye jaque mate, promoción y deshacer movimiento.",           tipo:"local" },
  { id:"game-052", nombre:"Whack-a-Mole",      categoria:"accion",     tags:["topo","reflejos","golpear","rapido"],      thumbnail:"assets/thumbs/juego-local-38.svg", embed_url:"games/juego-local-38.html",  descripcion:"Golpeá los topos que salen de los agujeros. ¡Cuidado con las bombas!",                       tipo:"local" },
  { id:"game-053", nombre:"Piano Tiles",       categoria:"casual",     tags:["piano","musica","ritmo","reflejos"],       thumbnail:"assets/thumbs/juego-local-39.svg", embed_url:"games/juego-local-39.html",  descripcion:"Tocá las teclas moradas que caen antes de que lleguen al fondo. Con sonido real.",            tipo:"local" },
  { id:"game-054", nombre:"Ahorcado",          categoria:"puzzle",     tags:["palabras","ahorcado","español","letras"],  thumbnail:"assets/thumbs/juego-local-40.svg", embed_url:"games/juego-local-40.html",  descripcion:"El clásico ahorcado en español con 20 palabras y pistas. Estadísticas de victorias.",        tipo:"local" },
  { id:"game-055", nombre:"8 Ball Pool",       categoria:"multijugador", tags:["pool","billar","bolas","8ball","online","versus"], thumbnail:"assets/thumbs/juego-local-41.svg", embed_url:"games/juego-local-41.html", descripcion:"Billar 8 Ball con física realista, efecto (english) y modo online 1v1. Jugá contra la CPU o contra un amigo con código de sala.", tipo:"local" },

  // ── IFRAME (pueden fallar dependiendo del sitio) ─────────────────────────
  { id:"game-004", nombre:"Krunker.io",      categoria:"accion",     tags:["fps","shooter","multi"],  thumbnail:"assets/thumbs/game-004.jpg", embed_url:"https://krunker.io/",                         descripcion:"FPS multijugador en el navegador.",                              tipo:"iframe" },
  { id:"game-005", nombre:"HexGL Racing",    categoria:"carreras",   tags:["naves","3d","webgl"],     thumbnail:"assets/thumbs/game-005.jpg", embed_url:"https://hexgl.bkcore.com/play/",              descripcion:"Carreras de naves futuristas en WebGL.",                         tipo:"iframe" },
  { id:"game-006", nombre:"Diep.io",         categoria:"accion",     tags:["tanques","io","multi"],   thumbnail:"assets/thumbs/game-006.jpg", embed_url:"https://diep.io/",                            descripcion:"Tanques multijugador. Evolucioná y destruí a todos.",            tipo:"iframe" },
  { id:"game-009", nombre:"Pacman",          categoria:"arcade",     tags:["clasico","laberinto"],    thumbnail:"assets/thumbs/game-009.jpg", embed_url:"https://freepacman.org/",                     descripcion:"Pacman clásico en el navegador.",                                tipo:"iframe" },
  { id:"game-010", nombre:"1v1.lol",          categoria:"accion",     tags:["construccion","shooter","multi"],  thumbnail:"assets/thumbs/game-010.svg", embed_url:"https://1v1.lol/",               descripcion:"Shooter con construcción de estructuras. El original del navegador.",    tipo:"iframe" },
  { id:"game-007", nombre:"Smash Karts",      categoria:"carreras",   tags:["karts","multi","armas","3d"],     thumbnail:"assets/thumbs/game-007.svg", embed_url:"https://smashkarts.io/",          descripcion:"Carreras de karts con armas. Multijugador online.",                       tipo:"iframe" },
  { id:"game-008", nombre:"Narrow One",       categoria:"accion",     tags:["arco","flecha","multi","estrategia"],thumbnail:"assets/thumbs/game-008.svg", embed_url:"https://narrow.one/",          descripcion:"Defensa del castillo con arco y flecha. Multijugador en tiempo real.",   tipo:"iframe" },
  { id:"game-002", nombre:"Shell Shockers",   categoria:"accion",     tags:["huevos","fps","multi","shooter"],  thumbnail:"assets/thumbs/game-002.svg", embed_url:"https://shellshock.io/",         descripcion:"FPS donde todos son huevos con armas. Multijugador online.",              tipo:"iframe" },
];

if (typeof module !== "undefined") module.exports = { juegos };
